apiVersion: v1
kind: Service
metadata:
  name: gke-front-button-app-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: gke-front-button-app